# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, restart the server process.

# Site settings
# If you look in the HTML files, you will see them accessed via
# {{ site.title }}, {{ site.email }}, and so on.


title: Theeta BV
description: >- # this means to ignore newlines until "baseurl:"
  Import, export and production. Netherlands, EU.
  Producer of Beckher appliacnes. Distributor of Sanosil disinfectants in Greece and Cyprus and Vallebelbo Miravento wine in Greece.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings

markdown: kramdown
permalink: pretty
# theme: minima
plugins:
  - jekyll-feed

### COLLECTIONS ### (i.e. product categories)
# output: true to render a page for each doc in the collection

# collections:
#   kitchen:
#     output: true
#     permalink: en/kitchen/:name

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
